### ISSUE TITLE
Division undefined error in Coverage

### ISSUE THREAD

**Issue by renep** [openbakery/CoverageReport#3]
@davetrux wrote:
Since upgrading to Xcode 8.3.1 the coverage task fails with a Division undefined error:

```
Caused by: java.lang.ArithmeticException: Division undefined
        at org.openbakery.coverage.model.SourceFile.getCoverage(SourceFile.groovy:138)
        at org.openbakery.coverage.model.SourceFile$getCoverage$2.call(Unknown Source)
        at org.openbakery.coverage.report.ReportData.getData(ReportData.groovy:91)
        at org.openbakery.coverage.report.XMLReport.generate(XMLReport.groovy:27)
        at org.openbakery.coverage.report.XMLReport$generate.call(Unknown Source)
        at org.openbakery.coverage.Report.createReport(Report.groovy:149)
        at org.openbakery.coverage.Report.create(Report.groovy:111)
        at org.openbakery.coverage.Report$create$1.callCurrent(Unknown Source)
        at org.openbakery.coverage.Report.create(Report.groovy:76)
        at org.openbakery.coverage.Report$create$0.call(Unknown Source)
        at org.openbakery.coverage.CoverageTask.coverage(CoverageTask.groovy:46)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```
It seems like the lines covered and lines executed are no longer being generated or pulled from the coverage report? 

All of our projects are experiencing this. 

See: https://github.com/openbakery/gradle-xcodePlugin/issues/349

**Comment by renep** [comment]
Looks like the coverage format has changed

**Comment by pnwaterloo** [comment]
@renep  Just wondering if you have any updates? Xcode v 8.3.2 & 8.3.3 are both giving "division undefined" error. 
Execution failed for task ':coverage'
> Disivion Undefined

**Comment by renep** [comment]
Nope. Have not found any time to fix this.

**Comment by eugenious** [comment]
I'm encountering this problem too. Maybe I could work on it and submit a PR?

**Comment by renep** [comment]
PR are always welcome, especially if they also contain unit tests 😀

**Comment by emileng** [comment]
Running into the same error.  Appreciate a fix to the code.

**Comment by eugenious** [comment]
okay, PR submitted, please take a look and let me know what you think

**Comment by eugenious** [comment]
how soon can you release the next version that contains this fix?

**Comment by renep** [comment]
I have already created version 0.9.4 today

**Comment by eugenious** [comment]
Don't you need to release 0.9.4 of this project, and then add it to the gradle-xcodePlugin project and release that project? I don't mean to appear pushy, just wondering if there's more that I can do or if it's up to you to release new versions of both projects?

**Comment by renep** [comment]
Latest develop version of the gradle-xcodePlugin (0.15.1.develop.115) includes 0.9.4. This version was created on the 14th Aug. (Every commit on the `develop` branch triggers a new develop build)
See also https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

**Comment by eugenious** [comment]
Oh great! I didn't realize that.

Thanks.

**Comment by eugenious** [comment]
I confirm that it's working as expected.
Will you release a new version of the gradle-xcodePlugin soon?
