### ISSUE TITLE
Some tests failing

### ISSUE THREAD

**Issue by eugenious** [openbakery/CoverageReport#4]
When I clone the project and run ".\gradlew test" not all the tests are passing.
70 tests completed, 44 failed.

One such failure is:
default report is txt

java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.get(TreeMap.java:278)
	at org.openbakery.coverage.report.ReportData$_closure1.doCall(ReportData.groovy:33)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.openbakery.coverage.report.ReportData.<init>(ReportData.groovy:31)
	at org.openbakery.coverage.Report.getReportData(Report.groovy:208)
	at org.openbakery.coverage.Report.createReport(Report.groovy:144)
	at org.openbakery.coverage.ReportSpecification.default report is txt(ReportSpecification.groovy:206)

**Comment by eugenious** [comment]
I tried it again on MacOS and all tests passed. I was using a Windows machine before. I would have expected this project to work just fine on Windows, since it's just parsing some text files, no?

**Comment by eugenious** [comment]
This package indeed requires the use of a Mac, since it does a two step conversion process: first it runs xcrun llvm-cov to generate a text file, then it parses the text file into a summary report.

So obviously won't work on Windows.

Not so obviously, I suppose?
